[machine]
name = "desktop"

[hub_connect]
address = "100.89.126.211:42069"

[zen]
profile_path = "~/.config/zen"

[projects.dsync]
path = "~/projects/dsync"
remote = "https://github.com/mflkee/dsync.git"
branch = "main"

[projects.dsync-v1]
path = "~/projects/dsync-v1"
branch = "main"

[projects.dotfiles]
path = "~/dotfiles"
remote = "https://github.com/mflkee/dotfiles.git"
branch = "main"
